out_dir: results
metric_best: f1
num_workers: 4
wandb:
  use: False
  project: LRGB-Benchmark-RandomSeed
  entity: project
dataset:
  format: PyG-TUDataset
  name: DD
  task: graph
  task_type: classification
  resample_negative: True
  transductive: False
  node_encoder: False
  node_encoder_name: Integer
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: Bond
  edge_encoder_bn: False
  split_mode: cv-stratifiedkfold-3
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 10
  model: DeepSet
  dim_pe: 16
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Subgraph_Mamba_L65
  n_heads: 4
  dim_hidden: 89  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.5
  attn_dropout: 0.4
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 89  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
seed: 0
