out_dir: results
metric_best: accuracy
wandb:
  use: true
  project: test
  entity: L65
dataset:
  format: PyG-GNNBenchmarkDataset
  name: MNIST
  task: graph
  task_type: classification
  transductive: false
  node_encoder: true
  node_encoder_name: LapPE
  node_encoder_bn: false
  edge_encoder: true
  edge_encoder_name: LinearEdge
  edge_encoder_bn: false
posenc_LapPE:
  enable: true
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 8
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Mamba_Hybrid_Degree_Noise
  layers: 3
  n_heads: 4
  dim_hidden: 52
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: false
  batch_norm: true
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 2
  dim_inner: 52
  batchnorm: false
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: false
optim:
  clip_grad_norm: true
  optimizer: adamW
  weight_decay: 0.01
  base_lr: 0.005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
seed: 0
